export const images = [
    "../images/autobot.png",
    "../images/decepticon.png",
    "../images/triforce.png",
    "../images/sonic.png",
    "../images/mario.png",
    "../images/mega-man.png",
    "../images/playstation.png"
    // "http://static.movingpackets.net/2013/12/github-logo-transparent.jpg",
    // "http://static.movingpackets.net/2013/12/github-logo-transparent.jpg",
    // "https://www.drupal.org/files/project-images/github_commits_logo.png",
    // "https://image.freepik.com/free-icon/github-logo-in-a-rounded-square_318-40761.jpg",
    // "http://www.pngall.com/wp-content/uploads/2016/04/Github-PNG-Image.png",
    // "https://cdn.afterdawn.fi/v3/news/original/github-logo.png",
    // "http://static.movingpackets.net/2013/12/github-logo-transparent.jpg",
    // "http://static.movingpackets.net/2013/12/github-logo-transparent.jpg",
    // "https://www.drupal.org/files/project-images/github_commits_logo.png",
    // "https://image.freepik.com/free-icon/github-logo-in-a-rounded-square_318-40761.jpg",
    // "http://www.pngall.com/wp-content/uploads/2016/04/Github-PNG-Image.png",
    // "https://cdn.afterdawn.fi/v3/news/original/github-logo.png",
    // "http://static.movingpackets.net/2013/12/github-logo-transparent.jpg",
    // "http://static.movingpackets.net/2013/12/github-logo-transparent.jpg",
    // "https://www.drupal.org/files/project-images/github_commits_logo.png",
    // "https://image.freepik.com/free-icon/github-logo-in-a-rounded-square_318-40761.jpg",
    // "http://www.pngall.com/wp-content/uploads/2016/04/Github-PNG-Image.png",
    // "https://www.drupal.org/files/project-images/github_commits_logo.png",
    // "https://image.freepik.com/free-icon/github-logo-in-a-rounded-square_318-40761.jpg",
]